added express server
smart-online-restro-booking-system/restro-booking-server pull request #1
Opened 2019-06-09 12:09 UTC by kavitamakariye

@Hdonge please review the PR.

2019-06-09 13:58 UTC, Hdonge requested changes
Some changes requested. Majorly infrastructure setup related changes required in early stage of application developments

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +const port = 2000;
Create a file name `config.json` and move configurations parameters there. Use `nconf` npm package to read configs from config file.
Configs can be created like

```
"environmant":{
      "production":{
                 "port":  3000
    },
      "development":{
                 "port":  5000
     }
}
```

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +const port = 2000;
https://github.com/Hdonge/nodejs-app/blob/master/app/lib/config.js refer this

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +    res.send('Hello!!');
It can be `res.send(200,{Status:'ok'});`

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +    console.log(`Listening on port ${port}!!`);
`console.log` should not be the part of the real time app. Use `log4js` npm package instead.

2019-06-09 13:58 UTC, Hdonge commented on package.json
> +    "url": "git+https://github.com/kavitamakariye/restro-booking-server.git"
Should be upstream url everywhere

2019-06-09 13:58 UTC, Hdonge commented on package.json
> +    "url": "git+https://github.com/kavitamakariye/restro-booking-server.git"
Should be upstream url everywhere

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +const port = 2000;
https://github.com/Hdonge/nodejs-app/blob/master/app/lib/server.js#L186

2019-06-09 13:58 UTC, Hdonge commented on index.js
> +const express = require('express');
`main` file of the application should be `index.js`.  But this is the code represent server is setup. Move this code inside `server.js` file and invoke that function from here. 

refer this https://github.com/Hdonge/nodejs-app/blob/master/app/index.js

2019-06-09 16:51 UTC, kavitamakariye commented
Made all the changes, please review it.

2019-06-10 01:42 UTC, Hdonge approved these changes
This is initial phase of application development where infrastructure setup is more important. Newly given reviews are mostly related to code styling and module creations. I will try to do that in next pr. You can follow them letter. 
Rest the task wise changes looks good. Approving it.

2019-06-10 01:42 UTC, Hdonge commented on config.json
> +               "port":  3000
After doing changes in any `.js Or . json ` please do indentation properly. Ctrl+shift+I

2019-06-10 01:42 UTC, Hdonge commented on server.js
> +//Required express, nconf and log4js
My intention was not to rename index.js to server.js but create a separate server file in that server related code can be moved and invoke that from index file

2019-06-10 01:42 UTC, Hdonge commented on server.js
> +const app = express();
Keep all the variable declarations at the top of the file. This is the part of code styling and make easy to debug.

2019-06-10 01:42 UTC, Hdonge commented on server.js
> +    res.send(200,{Status:'ok'});
Object property should always be in camel case.  Should be `status` here

2019-06-10 01:42 UTC, Hdonge commented on server.js
> +const log4js = require('log4js');
Configuration setup for log4js and nconf should be in separate module and those should be consume here.  
I will do in next pr. Will separate out everything.

2019-06-10 01:44 UTC, Hdonge commented
@kavitamakariye I am merging this pr and will create a task for me to do some changes related to infra setup.

2019-06-10 01:44 UTC, merged